analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
config-version: 2
macro-paths:
- macros
model-paths:
- models
models:
  my_new_project:
    example:
      materialized: table
name: my_new_project
profile: default
seed-paths:
- seeds
snapshot-paths:
- snapshots
target-path: target
test-paths:
- tests
version: 1.0.0