name: my_new_project
version: 1.0.0
config-version: 2

profile: my_new_project

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  bcmastercard:
    stg_tables:
      +materialized: view
    dim_tables:
      +materialized: table
    fct_tables:
      +materialized: table